Changes in the handling of reveled message indexes
decentralized-identity/bbs-signature pull request #14
Opened 2021-11-23 00:20 UTC by BasileiosKal

Changes in spkGen and spkVerify, in the direction discussed in the last WG call, of a more agile spec (aligned with option 1 from @tplooker's comment [here](https://github.com/decentralized-identity/bbs-signature/issues/10#issuecomment-939546272)). Specifically,

1. Added a revealed message indexes vector in the input to spkVerify
2. Added a recommendation for proof value encoding, similar to the one from ECDSA [RFC6979](https://datatracker.ietf.org/doc/html/rfc6979), with an additional preceding structure (taken from #10 , aligned with option 3 from the same [comment](https://github.com/decentralized-identity/bbs-signature/issues/10#issuecomment-939546272) as above).
3. Changed some of the indexing in spkGen and spkVerify to accommodate the changes above

2021-11-24 21:01 UTC, tplooker commented on spec.md
> +- RIdxs, integers vector (indices of revealed messages).
```suggestion
- RIdxs, vector of unsigned integers (indices of revealed messages).
```

2021-11-24 21:03 UTC, tplooker commented on spec.md
> +How a signature is to be encoded is not covered by the BBS+ spec itshelf. A common way is is to use a DER-encoded ASN.1 SEQUENCE for the proof value and append to that the list of indexes of revealed
```suggestion
How a signature is to be encoded is not covered by this document. (TODO perhaps add some additional information in the appendix)
```

2021-11-24 21:04 UTC, tplooker commented on spec.md
> +- RIdxs, integers vector (indices of revealed messages).
```suggestion
- RIdxs, vector of unsigned integers (indices of revealed messages).
```

2021-11-24 21:04 UTC, tplooker requested changes
Looking good, suggested a few changes

2021-11-24 23:29 UTC, BasileiosKal commented
Done applying changes!

2021-11-25 19:40 UTC, tplooker approved these changes

2021-11-28 19:30 UTC, tplooker commented
Waiting for discussion at next working group meeting to merge

2021-12-13 19:13 UTC, tplooker commented on spec.md
> +13. Y2 = d \* r3^ + h0 \* s^ + h\[ii\] \* m^\[i1\] + ... + h\[iR\] \* m^\[iR\] - T2 \* c
```suggestion
13. Y2 = d \* r3^ + h0 \* s^ + h\[i1\] \* m^\[i1\] + ... + h\[iR\] \* m^\[iR\] - T2 \* c
```

2021-12-13 19:14 UTC, merged